#!/bin/bash

# for when pdftotext just isn't quite enough

tifftemp=$(mktemp)

gs -dNOPAUSE -q -r500 -sDEVICE=tiffg4 -dBATCH -sOutputFile=${tifftemp}.tif $1

tesseract ${tifftemp}.tif ${1%%.pdf}
rm ${tifftemp}.tif
