#!/bin/bash

MAX_BRIGHTNESS="$(cat /sys/class/backlight/intel_backlight/max_brightness)"
BRIGHTNESS=/sys/class/backlight/intel_backlight/brightness

sudo cpupower frequency-set -g performance 1>/dev/null
echo $MAX_BRIGHTNESS | sudo tee $BRIGHTNESS 1>/dev/null
