#!/bin/bash

read -r -d '' HELP <<EOF
Usage: powersave.sh [options]

Sync or show status of my personal repositories.

    Command options:
    -h    Print this help documentation.
    -e    Use extreme lowest brightness.
EOF

LOW_BRIGHTNESS=150
MIN_BRIGHTNESS=1
BRIGHTNESS=/sys/class/backlight/intel_backlight/brightness

SET_BRIGHTNESS=$LOW_BRIGHTNESS

while getopts ":he" opt; do
    case $opt in
        h ) echo "$HELP"
            exit 0;;
        e ) SET_BRIGHTNESS=$MIN_BRIGHTNESS
            ;;
        ? ) echo "Invalid option -${OPTARG}..."
            echo "$HELP"
            exit 1;;
    esac
done
shift $(($OPTIND - 1))


sudo powertop --auto-tune
sudo cpupower frequency-set -g powersave 1>/dev/null
echo $SET_BRIGHTNESS | sudo tee $BRIGHTNESS 1>/dev/null

exit 0
