#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do 
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

ETC="${DIR}/.."
ETC=$(realpath "$ETC")

info () {
    printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit 1
}

# main
if [ "x$1" = "x-f" ] ; then
    force=true
else
    force=false
fi

cd $ETC
for config in $(ls -d */ | grep -Ev '^_') ; do
    stow "$config"
    if [ $? != 0 ] ; then
        fail "couldn't install $config"
    fi
done

echo ''
echo '  All installed!'
