#!/usr/bin/env dash
# jcpetkovich - 2016 (c) wtfpl

# browser
# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# .............................................................. Browser Wrapper

# I'm a simple man
$BROWSER $@
