#!/bin/bash

# Colemak with closer to an ergodox keyboard setup

setxkbmap us -variant colemak

# Remove all modifiers that I'm going to change
xmodmap -e 'clear Control'
xmodmap -e 'clear Mod5'
xmodmap -e 'clear Mod4'
xmodmap -e 'clear Mod1'

if [[ $(hostname) == "tricorder" ]]; then
    xmodmap -e 'keycode 23 = Escape Escape Escape Escape Escape Escape Escape'
    xmodmap -e 'keycode 133 = Tab Tab Tab Tab Tab Tab Tab'
    xmodmap -e 'keycode 108 = Control_R Control_R Control_R Control_R Control_R Control_R Control_R'
    xmodmap -e 'keycode 134 = ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift'
    xmodmap -e 'keycode 105 = Super_L Super_L Super_L Super_L Super_L Super_L Super_L'
    xmodmap -e 'keycode 37 = Super_L Super_L Super_L Super_L Super_L Super_L Super_L'
    xmodmap -e 'keycode 135 = ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift'
else
    # Rebind keys so that they are easier to map
    xmodmap -e 'keycode 23 = Escape Escape Escape Escape Escape Escape Escape'
    xmodmap -e 'keycode 66 = Tab Tab Tab Tab Tab Tab Tab'
    xmodmap -e 'keycode 108 = Control_L Control_L Control_L Control_L Control_L Control_L Control_L'
    xmodmap -e 'keycode 134 = ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift'
    xmodmap -e 'keycode 133 = Super_L Super_L Super_L Super_L Super_L Super_L Super_L'
    xmodmap -e 'keycode 135 = ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift ISO_Level3_Shift'
fi

# No left control key allowed!
# xmodmap -e 'keycode 37 = '

# Rebind modifiers
xmodmap -e 'add Control = Control_L'
xmodmap -e 'add Control = Control_R'
xmodmap -e 'add Mod1 = Alt_L'
xmodmap -e 'add Mod4 = Super_L'
xmodmap -e 'add Mod5 = ISO_Level3_Shift'

xset r rate 250
