#!/usr/bin/env bash

where=$(echo home out \
							 | tr ' ' '\n' \
							 | sudo -u jcp rofi -dmenu -terminal st)

if [ $where == "home" ]; then
		echo "nameserver $HOME_SERVER" | sudo tee /etc/resolv.conf.head > /dev/null
		sudo wpa_cli reconfigure
else
		echo "" | sudo tee /etc/resolv.conf.head > /dev/null
		sudo wpa_cli reconfigure
fi
