#!/usr/bin/env dash

# Script to launch emacs.
# Check if we are opening the emacs client in a terminal, then set
# xterm-256color as TERM since that seems to reproduce colourschemes
# better than the alternatives.
for arg in $@; do
    if [ "$arg" = "-t" ]; then
        TERM=xterm-256color
        NOWAIT=false
    fi
done

if [ "$NOWAIT" = true ]; then
    emacsclient -a '' -c -n $@
else
    emacsclient -a '' -c $@
fi
