#!/bin/bash

ADDED=$(git diff --word-diff=porcelain | grep -e '^+[^+]' | wc -m | awk '{ print ($0 / 5) }')
REMOVED=$(git diff --word-diff=porcelain | grep -e '^-[^-]' | wc -m)

echo " ( $ADDED - $REMOVED ) / 5 " | bc
