#!/usr/bin/env dash
# Jean-Christophe Petkovich - 2016 (c) wtfpl
# [ $TRACE ] && CHILD="is $@" . $PARENT

# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# ........................................................ Is (state) operations

# Usage: is <msg>, see functions/is

msg=$1
[ $msg ] && shift || usage $0
if [ -e ${0%/is}/functions/is/$msg ] ;then
  . ${0%/is}/functions/is/$msg $@
else
  usage $0
fi
