#!/usr/bin/env bash
## define your terminal in "TERM=<your-terminal>, defaults to sakura
## assumes your password store in ~/.password-store (default)
## the script uses rofi (alised to dmenu in my setup), to use dmenu just replace "rofi -dmenu" with "dmenu"

TERM=st

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

echo -e "password view\npassword edit\nnew entry\nremove entry" | rofi -dmenu -location 1 -lines 4 -width 100 -p SELECT: > /tmp/x

grep -o view < /tmp/x && printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@" -location 1 -lines 10 -width 100 -p PASS: > /tmp/a && notify-send -u critical "$(pass show $(< /tmp/a) 2>/dev/null)" && exit
grep -o edit < /tmp/x && printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@" -location 1 -lines 10 -width 100 -p PASS: > /tmp/a && $TERM -e pass edit $(< /tmp/a) && exit
grep -o new < /tmp/x && cat /dev/null | rofi -dmenu -location 1 -lines 10 -width 100 -p PASS: > /tmp/a && $TERM -e pass edit $(< /tmp/a) && exit
grep -o remove < /tmp/x && printf '%s\n' "${password_files[@]}" | rofi -dmenu "$@" -location 1 -lines 10 -width 100 -p PASS: > /tmp/a && $TERM -e pass rm $(< /tmp/a) 2>/dev/null && exit
