#!/usr/bin/env dash
# jcpetkovich - 2016 (c) wtfpl

# X11 System
# ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂

# ..................................................................... Terminal

export SHELL=/bin/fish

eval /usr/bin/st $@

# vim: set ft=sh: #
